variables:
  CURRENT_STAGING: staging-35test
  APP: 'browser-sdk'
  CURRENT_CI_IMAGE: 25
  BUILD_STABLE_REGISTRY: '486234852809.dkr.ecr.us-east-1.amazonaws.com'
  CI_IMAGE: '$BUILD_STABLE_REGISTRY/ci/$APP:$CURRENT_CI_IMAGE'

cache:
  key: dependencies
  paths:
    - node_modules/

stages:
  - test

format:
  stage: test
  tags: ['runner:main', 'size:large']
  image: $CI_IMAGE
  script:
    - bash scripts/test-commit.sh
